# escape=`

ARG REPO=docker.io/spheresoftnet/net.framework.sdk
FROM $REPO:4.8.T4.2019


MAINTAINER Holger Boskugel, github.com/SphereSoftNET

LABEL org.opencontainers.image.description=".NET Framework 4.8 SDK (2019-LTSC) extension Text Templating (T4) and GIT"
LABEL org.opencontainers.image.authors="Holger Boskugel, github.com/SphereSoftNET"
LABEL org.opencontainers.image.vendor="SphereSoft.NET"
LABEL org.opencontainers.image.url="https://hub.docker.com/repository/docker/spheresoftnet/net.framework.sdk"
LABEL org.opencontainers.image.source="https://github.com/SphereSoftNET/Docker/blob/master/Images/Dockerfile.net.framework.sdk.4.8.T4.GIT.2019"
LABEL org.opencontainers.image.base.name="docker.io/spheresoftnet/net.framework.sdk:4.8.T4.2019"
LABEL org.opencontainers.image.base.digest="1253b2b6895ac8a80c9cfb060cbfce5eb3c2226f666390bd7a44c16f552f1c10"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.version="2023.08.16"
LABEL org.opencontainers.image.created="2023-08-16"


SHELL ["cmd", "/S", "/C"]


# Install GIT
RUN echo Resolving / Downloading ... `
    && curl -fSLo Git-64-bit.exe https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.3/Git-2.41.0.3-64-bit.exe `
    && echo Installing ... `
    && start /w Git-64-bit /SILENT /NORESTART `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del Git-64-bit.exe


SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
