# escape=`

ARG REPO=mcr.microsoft.com/dotnet/framework/sdk
FROM $REPO:4.8-windowsservercore-ltsc2019


MAINTAINER Holger Boskugel, github.com/SphereSoftNET

LABEL maintainer="Holger Boskugel, github.com/SphereSoftNET"
LABEL decsription=".NET Framework 4.8 (2019-LTSC) extension Text Templating (T4)"


SHELL ["cmd", "/S", "/C"]


# Install VS component Microsoft.VisualStudio.Component.TextTemplating
RUN curl -fSLo vs_BuildTools.exe https://aka.ms/vs/17/release/vs_BuildTools.exe `
    && start /w vs_BuildTools ^ `
        --add Microsoft.VisualStudio.Component.TextTemplating ^ `
        --quiet --norestart --nocache --wait `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del vs_BuildTools.exe


SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
