# escape=`

ARG REPO=mcr.microsoft.com/dotnet/framework/sdk
FROM $REPO:4.8-windowsservercore-ltsc2019


MAINTAINER Holger Boskugel, github.com/SphereSoftNET

LABEL org.opencontainers.image.description=".NET Framework 4.8 SDK (2019-LTSC) extension Text Templating (T4)"
LABEL org.opencontainers.image.authors="Holger Boskugel, github.com/SphereSoftNET"
LABEL org.opencontainers.image.vendor="SphereSoft.NET"
LABEL org.opencontainers.image.url="https://hub.docker.com/repository/docker/spheresoftnet/net.framework.sdk"
LABEL org.opencontainers.image.source="https://github.com/SphereSoftNET/Docker/blob/master/Images/Dockerfile.net.framework.sdk.4.8.T4.2019"
LABEL org.opencontainers.image.base.name="mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019"
LABEL org.opencontainers.image.base.digest="a6e1586b48076f988a1c8a25b4c3cdecd585c4f99497127bb3432f7d72262704"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.version="2023.08.16"
LABEL org.opencontainers.image.created="2023-08-16"


SHELL ["cmd", "/S", "/C"]


# Install VS component Microsoft.VisualStudio.Component.TextTemplating
RUN echo Resolving / Downloading ... `
    && curl -fSLo vs_BuildTools.exe https://aka.ms/vs/17/release/vs_BuildTools.exe `
    && echo Installing ... `
    && start /w vs_BuildTools `
        --add Microsoft.VisualStudio.Component.TextTemplating `
        --quiet --norestart --nocache --wait `
    && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del vs_BuildTools.exe


SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
